name: Flat_gbif_test

on:
  push:
    paths:
      - .github/workflows/flat_gbif.yml # Only run a new workflow every time this file (flat_gbif.yml) file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '30 14 * * *' # Run this every day at 14:30

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: # This workflow has 3 steps
      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # This step installs Deno, which is a new Javascript runtime that improves on Node. We'll use it for postprocessing later
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10x
      # The third step is a Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch data 
        uses: githubocto/flat@v3
        with:
          http_url: https://api.gbif.org/v1/occurrence/count?country=MG&taxonKey=6&datasetKey=50c9509d-22c7-4a22-a47d-8c48425ef4a7 # The data to fetch every day
          downloaded_filename: gbif_mad_inat.json # The http_url gets saved and renamed in our repository as btc-price.json
